spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cky13291983702
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf-8&useSSL=false


